---
systemd:
  units:
    - name: flanneld.service
      enable: true
    - name: docker.service
      enable: true
      dropins:
        - name: 40-flannel.conf
          contents: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
    - name: kubelet.path
      enable: true
      contents: |
        [Unit]
        Description=Watch for kubeconfig
        [Path]
        PathExists=/etc/kubernetes/kubeconfig
        [Install]
        WantedBy=multi-user.target
    - name: kubelet.service
      enable: true
      contents: |
        [Service]
        EnvironmentFile=-/etc/environment
        EnvironmentFile=/run/flannel/subnet.env
        Environment=KUBELET_ACI=quay.io/coreos/hyperkube
        Environment=KUBELET_VERSION=v1.3.0-beta.2_coreos.0
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/bin/mkdir -p /srv/kubernetes/manifests
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/checkpoint-secrets
        ExecStart=/bin/bash -c '/usr/lib/coreos/kubelet-wrapper \
          --api-servers=https://[fc4f:b597:4296:b8ca:13c8:9f17:dd30:811d]:443 \
          --kubeconfig=/etc/kubernetes/kubeconfig \
          --lock-file=/var/run/lock/kubelet.lock \
          --exit-on-lock-contention \
          --config=/etc/kubernetes/manifests \
          --allow-privileged \
          --hostname-override=$${FLANNEL_SUBNET%/*} \
          --node-labels=master=true \
          --minimum-container-ttl-duration=3m0s \
          --cluster_dns=10.3.0.10 \
          --cluster_domain=cluster.local \
          '
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target

storage:
  {{ if index . "pxe" }}
  disks:
    - device: /dev/sda
      wipe_table: true
      partitions:
        - label: ROOT
  filesystems:
    - name: rootfs
      mount:
        device: "/dev/sda1"
        format: "ext4"
        create:
          force: true
          options:
            - "-LROOT"
  {{else}}
  filesystems:
    - name: rootfs
      mount:
        device: "/dev/disk/by-label/ROOT"
        format: "ext4"
  {{end}}
  files:
    - path: /etc/kubernetes/empty
      filesystem: rootfs
      mode: 0644
      contents:
        inline: |
          empty

{{ if index . "ssh_authorized_keys" }}
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
