apiVersion: v1
kind: Service
metadata:
  name: bootcfg
  namespace: kubermesh
spec:
  selector:
    app: bootcfg
  ports:
  - name: http
    port: 80
    targetPort: 8085
    nodePort: 30085
  type: NodePort
