apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bootcfg
  namespace: kubermesh
spec:
  template:
    metadata:
      labels:
        app: bootcfg
    spec:
      containers:
      - name: bootcfg
        image: kubermesh/bootcfg
        ports:
        - containerPort: 8085
        volumeMounts:
        - mountPath: /var/lib/bootcfg/assets/kubernetes
          name: kubernetes-config
      volumes:
      - name: kubernetes-config
        hostPath:
          path: /etc/kubernetes
