apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dnsmasq
  namespace: kubermesh
spec:
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          image: quay.io/coreos/dnsmasq
          name: dnsmasq
          args:
          - --no-daemon
          - --enable-tftp
          - --tftp-root=/var/lib/tftpboot
          - --dhcp-userclass=set:ipxe,iPXE
          - --dhcp-boot=tag:#ipxe,undionly.kpxe
          - --dhcp-boot=tag:ipxe,http://bootcfg.kubermesh:30085/boot.ipxe
          - --log-queries
          - --log-dhcp
          - --interface=eth1
          - --bind-dynamic
          - --dhcp-range=172.18.0.2,172.18.0.6
          - --address=/bootcfg.kubermesh/172.18.0.1
